UPDATE Resources 
SET Frequency = 4
WHERE ResourceType = 'RESOURCE_MAGIC_MASHROOM';

INSERT INTO ProjectCompletionModifiers
	(ProjectType, ModifierId)
VALUES	('PROJECT_MARISA_AND_SEX_MUSHROOM', 'PROJECT_GRANT_UNIT_MARISA') ,
('PROJECT_MARISA_AND_SEX_MUSHROOM_1', 'PROJECT_UNIT_MARISA_PROMOTION') ,
('PROJECT_MARISA_AND_SEX_MUSHROOM_2', 'PROJECT_UNIT_MARISA_PROMOTION') ,
('PROJECT_MARISA_AND_SEX_MUSHROOM_3', 'PROJECT_UNIT_MARISA_PROMOTION') ,
('PROJECT_MARISA_AND_SEX_MUSHROOM_4', 'PROJECT_UNIT_MARISA_PROMOTION') ,
('PROJECT_MARISA_AND_SEX_MUSHROOM_5', 'PROJECT_UNIT_MARISA_PROMOTION') ,
('PROJECT_MARISA_AND_SEX_MUSHROOM_6', 'PROJECT_UNIT_MARISA_PROMOTION') ,
('PROJECT_DOLLS_WAR_1', 'PROJECT_UNIT_SHANGHAI_PROMOTION') ,
('PROJECT_DOLLS_WAR_2', 'PROJECT_UNIT_SHANGHAI_PROMOTION') ,
('PROJECT_DOLLS_WAR_3', 'PROJECT_UNIT_SHANGHAI_PROMOTION') ,

('PROJECT_RECALL_GOD', 'PROJECT_GRANT_UNIT_SHINKI') ,
('PROJECT_GOD_POWER', 'PROJECT_UNIT_SHINKI_PROMOTION'),
('PROJECT_GOD_POWER_2', 'PROJECT_UNIT_SHINKI_PROMOTION'),
('PROJECT_GOD_POWER_FINAL', 'PROJECT_UNIT_SHINKI_PROMOTION');

-- 测试用代码
-- UPDATE Building_YieldChanges 
-- SET YieldChange = 50
-- WHERE BuildingType = 'BUILDING_PALACE';
