-- 工业区强化(Industrial stronger)
-- REPLACE INTO Requirements
-- 		(RequirementId,RequirementType)		
-- VALUES	('CITY_HAS_WORKSHOP','REQUIREMENT_CITY_HAS_BUILDING'),
-- ('CITY_HAS_FACTORY','REQUIREMENT_CITY_HAS_BUILDING'),
-- ('CITY_HAS_ELECTRONICS_FACTORY','REQUIREMENT_CITY_HAS_BUILDING'),
-- ('CITY_HAS_POWER_PLANT','REQUIREMENT_CITY_HAS_BUILDING'),
-- ('CITY_HAS_HANSA','REQUIREMENT_CITY_HAS_DISTRICT');


-- REPLACE INTO RequirementArguments 
-- 		(RequirementId,Name,Value)		
-- VALUES 	('CITY_HAS_WORKSHOP','BuildingType','BUILDING_WORKSHOP'),
-- ('REQUIRES_CITY_HAS_FACTORY','BuildingType','BUILDING_FACTORY'),
-- ('CITY_HAS_ELECTRONICS_FACTORY','BuildingType','BUILDING_ELECTRONICS_FACTORY'),
-- ('CITY_HAS_POWER_PLANT','BuildingType','BUILDING_POWER_PLANT'),
-- ('CITY_HAS_HANSA','DistrictType','DISTRICT_HANSA');


-- REPLACE INTO RequirementSets 
-- 	(RequirementSetId,RequirementSetType)
-- VALUES 	('REQUIRES_CITY_HAS_WORKSHOP','REQUIREMENTSET_TEST_ALL'),
-- ('REQUIRES_CITY_HAS_FACTORY','REQUIREMENTSET_TEST_ALL'),
-- ('REQUIRES_CITY_HAS_ELECTRONICS_FACTORY','REQUIREMENTSET_TEST_ALL'),
-- ('REQUIRES_CITY_HAS_POWER_PLANT','REQUIREMENTSET_TEST_ALL'),
-- ('REQUIRES_CITY_HAS_INDUSTRIAL_ZONE','REQUIREMENTSET_TEST_ALL'),
-- ('REQUIRES_CITY_HAS_HANSA','REQUIREMENTSET_TEST_ALL');


-- REPLACE INTO RequirementSetRequirements
-- 		(RequirementSetId,RequirementId)
-- VALUES	('REQUIRES_CITY_HAS_WORKSHOP','CITY_HAS_WORKSHOP'),
-- ('REQUIRES_CITY_HAS_FACTORY','CITY_HAS_FACTORY'),
-- ('REQUIRES_CITY_HAS_ELECTRONICS_FACTORY','CITY_HAS_ELECTRONICS_FACTORY'),
-- ('REQUIRES_CITY_HAS_POWER_PLANT','CITY_HAS_POWER_PLANT'),
-- ('REQUIRES_CITY_HAS_HANSA','CITY_HAS_HANSA');


-- 提升工业区建筑产能(由2/3/4提升至4/8/12)
UPDATE Building_YieldChanges
SET YieldChange = 4 
WHERE BuildingType="BUILDING_WORKSHOP" AND YieldType="YIELD_PRODUCTION";

UPDATE Building_YieldChanges
SET YieldChange = 8
WHERE BuildingType="BUILDING_FACTORY" AND YieldType="YIELD_PRODUCTION";

UPDATE Building_YieldChanges
SET YieldChange = 8
WHERE BuildingType="BUILDING_ELECTRONICS_FACTORY" AND YieldType="YIELD_PRODUCTION";

UPDATE Building_YieldChanges
SET YieldChange = 12
WHERE BuildingType="BUILDING_POWER_PLANT" AND YieldType="YIELD_PRODUCTION"; 


-- 每个工业区建筑为城市建造(包括区域/奇观)提供5%产能
-- INSERT INTO BuildingModifiers(BuildingType,ModifierId)
-- VALUES
-- ('BUILDING_WORKSHOP','BUILDING_WORKSHOP_FASTER_BUILDTIME_DISTRICT'),
-- ('BUILDING_WORKSHOP','BUILDING_WORKSHOP_FASTER_BUILDTIME_WONDER'),
-- ('BUILDING_FACTORY','BUILDING_FACTORY_FASTER_BUILDTIME_DISTRICT'),
-- ('BUILDING_FACTORY','BUILDING_FACTORY_FASTER_BUILDTIME_WONDER'),
-- ('BUILDING_ELECTRONICS_FACTORY','BUILDING_ELECTRONICS_FACTORY_FASTER_BUILDTIME_DISTRICT'),
-- ('BUILDING_ELECTRONICS_FACTORY','BUILDING_ELECTRONICS_FACTORY_FASTER_BUILDTIME_WONDER'),
-- ('BUILDING_POWER_PLANT','BUILDING_POWER_PLANT_FASTER_BUILDTIME_DISTRICT'),
-- ('BUILDING_POWER_PLANT','BUILDING_POWER_PLANT_FASTER_BUILDTIME_WONDER');

-- INSERT INTO Modifiers(ModifierId,ModifierType,SubjectRequirementSetId)
-- VALUES 
-- ('BUILDING_WORKSHOP_FASTER_BUILDTIME_DISTRICT','MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION','REQUIRES_CITY_HAS_WORKSHOP'),
-- ('BUILDING_WORKSHOP_FASTER_BUILDTIME_WONDER','MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION','REQUIRES_CITY_HAS_WORKSHOP'),
-- ('BUILDING_FACTORY_FASTER_BUILDTIME_DISTRICT','MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION','REQUIRES_CITY_HAS_FACTORY'),
-- ('BUILDING_FACTORY_FASTER_BUILDTIME_WONDER','MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION','REQUIRES_CITY_HAS_FACTORY'),
-- ('BUILDING_ELECTRONICS_FACTORY_FASTER_BUILDTIME_DISTRICT','MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION','REQUIRES_CITY_HAS_ELECTRONICS_FACTORY'),
-- ('BUILDING_ELECTRONICS_FACTORY_FASTER_BUILDTIME_WONDER','MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION','REQUIRES_CITY_HAS_ELECTRONICS_FACTORY'),
-- ('BUILDING_POWER_PLANT_FASTER_BUILDTIME_DISTRICT','MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION','REQUIRES_CITY_HAS_POWER_PLANT'),
-- ('BUILDING_POWER_PLANT_FASTER_BUILDTIME_WONDER','MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION','REQUIRES_CITY_HAS_POWER_PLANT');

-- INSERT INTO ModifierArguments(ModifierId,Name,Value)
-- VALUES 
-- ('BUILDING_WORKSHOP_FASTER_BUILDTIME_DISTRICT','Amount',5),
-- ('BUILDING_WORKSHOP_FASTER_BUILDTIME_WONDER','Amount',5),
-- ('BUILDING_FACTORY_FASTER_BUILDTIME_DISTRICT','Amount',5),
-- ('BUILDING_FACTORY_FASTER_BUILDTIME_WONDER','Amount',5),
-- ('BUILDING_ELECTRONICS_FACTORY_FASTER_BUILDTIME_DISTRICT','Amount',5),
-- ('BUILDING_ELECTRONICS_FACTORY_FASTER_BUILDTIME_WONDER','Amount',5),
-- ('BUILDING_POWER_PLANT_FASTER_BUILDTIME_DISTRICT','Amount',5),
-- ('BUILDING_POWER_PLANT_FASTER_BUILDTIME_WONDER','Amount',5);


-- -- 工业区本身提供10%产能
-- INSERT INTO DistrictModifiers
-- (DistrictType,ModifierId)
-- VALUES 
-- ('DISTRICT_INDUSTRIAL_ZONE','DISTRICT_INDUSTRIAL_ZONE_FASTER_BUILDTIME_DISTRICT'),
-- ('DISTRICT_INDUSTRIAL_ZONE','DISTRICT_INDUSTRIAL_ZONE_FASTER_BUILDTIME_WONDER'),
-- ('DISTRICT_HANSA','DISTRICT_HANSA_FASTER_BUILDTIME_DISTRICT'),
-- ('DISTRICT_HANSA','DISTRICT_HANSA_FASTER_BUILDTIME_WONDER');

-- INSERT INTO Modifiers(ModifierId,ModifierType,SubjectRequirementSetId)
-- VALUES 
-- ('DISTRICT_INDUSTRIAL_ZONE_FASTER_BUILDTIME_DISTRICT','MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION','REQUIRES_CITY_HAS_INDUSTRIAL_ZONE'),
-- ('DISTRICT_INDUSTRIAL_ZONE_FASTER_BUILDTIME_WONDER','MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION','REQUIRES_CITY_HAS_INDUSTRIAL_ZONE'),
-- ('DISTRICT_HANSA_FASTER_BUILDTIME_DISTRICT','MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION','REQUIRES_CITY_HAS_HANSA'),
-- ('DISTRICT_HANSA_FASTER_BUILDTIME_WONDER','MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION','REQUIRES_CITY_HAS_HANSA');

-- INSERT INTO ModifierArguments(ModifierId,Name,Value)
-- VALUES 
-- ('DISTRICT_INDUSTRIAL_ZONE_FASTER_BUILDTIME_DISTRICT','Amount',10),
-- ('DISTRICT_INDUSTRIAL_ZONE_FASTER_BUILDTIME_WONDER','Amount',10),
-- ('DISTRICT_HANSA_FASTER_BUILDTIME_DISTRICT','Amount',10),
-- ('DISTRICT_HANSA_FASTER_BUILDTIME_WONDER','Amount',10);
