-- 待测试内容
-- 自定义ModifierType是否有效(首都地块+2魅力，单城奇观加速)
-- MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION是否会触发多次

INSERT INTO Types
(Type,Kind)
VALUES
('TRAIT_CIVILIZATION_CIPITAL_APPEAL','KIND_TRAIT'),
('MODIFIER_SINGLE_CITY_ADJUST_DISTRICT_PRODUCTION','KIND_MODIFIER'),
('MODIFIER_SINGLE_CITY_ADJUST_WONDER_PRODUCTION','KIND_MODIFIER'),
('MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_APPEAL','KIND_MODIFIER');

INSERT INTO DynamicModifiers
(ModifierType,CollectionType,EffectType)
VALUES
('MODIFIER_SINGLE_CITY_ADJUST_DISTRICT_PRODUCTION','COLLECTION_OWNER','EFFECT_ADJUST_ALL_DISTRICTS_PRODUCTION'),
('MODIFIER_SINGLE_CITY_ADJUST_WONDER_PRODUCTION','COLLECTION_OWNER','EFFECT_ADJUST_WONDER_PRODUCTION'),
('MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_APPEAL','COLLECTION_PLAYER_CAPITAL_CITY','EFFECT_ADJUST_CITY_APPEAL');

INSERT INTO Modifiers
(ModifierId,ModifierType,SubjectRequirementSetId)
VALUES
('TEST_CITY_WONDER_FASTER','MODIFIER_SINGLE_CITY_ADJUST_WONDER_PRODUCTION',NULL),
('TEST_CITY_BUILDING_FASTER','MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION',NULL),
('TEST_CITY_DISTRICT_FASTER','MODIFIER_SINGLE_CITY_ADJUST_DISTRICT_PRODUCTION',NULL),
('TEST_ADD_CIPITAL_APPEAL','MODIFIER_PLAYER_CAPITAL_CITY_ADJUST_CITY_APPEAL',NULL);

INSERT INTO ModifierArguments
(ModifierId,Name,Value)
VALUES
('TEST_CITY_WONDER_FASTER','Amout',100),
('TEST_CITY_DISTRICT_FASTER','Amout',100),
('TEST_ADD_CIPITAL_APPEAL','Amout',2);

INSERT INTO ModifierArguments
(ModifierId,Name,Value)
SELECT 'TEST_CITY_BUILDING_FASTER','BuildingType',GROUP_CONCAT(BuildingType) FROM Buildings;

INSERT INTO ModifierArguments
(ModifierId,Name,Value)
VALUES
('TEST_CITY_BUILDING_FASTER','Amount',100);


INSERT INTO Traits
(TraitType,Name,Description)
VALUES
('TRAIT_CIVILIZATION_CIPITAL_APPEAL','LOC_TRAIT_CIVILIZATION_CIPITAL_APPEAL_NAME','LOC_TRAIT_CIVILIZATION_CIPITAL_APPEAL_DESCRIPTION');

INSERT INTO TraitModifiers
(TraitType,ModifierId)
VALUES
('TRAIT_CIVILIZATION_CIPITAL_APPEAL','TEST_ADD_CIPITAL_APPEAL');

INSERT INTO CivilizationTraits
(CivilizationType,TraitType)
VALUES
('CIVILIZATION_CHINA','TRAIT_CIVILIZATION_CIPITAL_APPEAL');

INSERT INTO BuildingModifiers
(BuildingType,ModifierType)
VALUES
('BUILDING_MONUMENT','TEST_CITY_WONDER_FASTER'),
('BUILDING_MONUMENT','TEST_CITY_DISTRICT_FASTER');
